#!/bin/bash

set -e

stemcell_jammy_path=$PWD/stemcell/*.tgz
stemcell_bionic_path=$PWD/stemcell-bionic/*.tgz
bpm_release_path=$PWD/bpm/*.tgz

if [ -n "$FOCUS" ]; then
  echo "------------------------------------------------------------------"
  echo "FOCUS is set. Will only run tests matching '$FOCUS'"
  echo "Docker won't be stopped afterwards, so you can debug the test."
  echo "------------------------------------------------------------------"
  FOCUS_ARG="-focus $FOCUS"
fi

cd ${REPO_ROOT:?required}
echo "----- Pulling in any git submodules..."
git submodule update --init --recursive --force

echo "----- Starting BOSH"

./ci/scripts/start-bosh.sh

function stop_docker() {
  echo "----- stopping docker"
  service docker stop
}

if [ -z "$FOCUS" ]; then