#!/bin/bash

set -eu

stemcell_path=$PWD/stemcell/*.tgz
bpm_release_path=$PWD/bpm/*.tgz

cd ${REPO_ROOT:?required}
echo "----- Pulling in any git submodules..."
git submodule update --init --recursive --force

echo "----- Starting BOSH"

./