#!/bin/bash
APP_DIR=/var/vcap/jobs/keepalived
PKG_DIR=/var/vcap/packages/keepalived
BIN_DIR=${PKG_DIR}/bin
SBIN_DIR=${PKG_DIR}/sbin
CONF_DIR=${APP_DIR}/config
RUN_DIR=/var/vcap/sys/run/keepalived
LOG_DIR=/var/vcap/sys/log/keepalived

source /var/vcap/packages/keepalived/common/utils.sh

interface_for_ip() {
    local ip=$1
    local network=""

    for route in $(ip route show scope link | cut -d " " -f1); do
        if [[ $(ip_in_network $route $ip) == 0 ]]; then
            network=$route
            break
        fi
    done

    if [[ -z $network ]]; then
        echo "Could not determine an interface for requested VIP: $ip"
        exit 1
    fi

    interface=$(ip route show scope link | grep "${network}" | cut -d " " -f3)
    if [[ -z ${interface} ]]; then
        echo "Could not find the previously found network ${network} in the routing tables. Something is very wrong"
        exit 1
    fi
    echo "${interface}"
}

binary_ip() {
    string_ip=$1
    i=1
    binary_ip=0
    for octet in $(echo "$string_ip" | tr -s "." " "); do
        binary_ip=$(($binary_ip + ($octet<<(32-(8*$i)))))
        i=$(($i+1))
    done
    echo ${binary_ip}
}

binary_mask() {
    bits=$1
    full_mask=$(((2**32)-1))
    mask=$((((2**32)-1)-((2**(32-$bits))-1)))
    echo $mask
}

ip_in_network() {
    network=$1
    target_ip=$2

    net_ip=$(echo $network | cut -d "/" -f1)
    net_mask=$(echo $network | cut -d "/" -f2)

    net_ip_binary=$(binary_ip "$net_ip")
    target_ip_binary=$(binary_ip "$target_ip")
  