compilation:
  workers: 5
  reuse_compilation_vms: true
  vm_type: haproxy
  network: haproxy

vm_types:
- name: haproxy
  cloud_properties:
    name: random

networks:
  - name: haproxy
    subnets:
      - cloud_properties:
          name: random
        range: 10.244.50.0/24