
---

groups:
  - name: haproxy-boshrelease
    jobs:
      - unit-tests
      - unit-tests-pr
      - acceptance-tests
      - acceptance-tests-pr
      - pre
      - rc
      - shipit
      - major
      - minor
      - autobump-dependencies

jobs:
  - name: unit-tests
    public: true
    serial: true
    plan:
    - do:
      - get: git
        trigger: true
      - task: lint
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: iacbox.common.repositories.cloud.sap/haproxy-boshrelease-testflight
              tag:        latest
              username:   ((docker.username))
              password:   ((docker.password))
          inputs:
            - { name: git }
          caches:
          - path: git/vendor/cache
          - path: git/.bundle
          run:
            path: ./git/ci/scripts/lint
            args: []
          params:
            REPO_ROOT: git
      - task: unit-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: iacbox.common.repositories.cloud.sap/haproxy-boshrelease-testflight
              tag:        latest
              username:   ((docker.username))
              password:   ((docker.password))
          inputs:
            - { name: git }

          caches:
          - path: git/vendor/cache
          - path: git/.bundle
          run:
            path: ./git/ci/scripts/unit-tests
            args: []
          params:
            REPO_ROOT: git
      on_failure:
        put: notify
        params:
          channel:  "#haproxy-boshrelease"
          username: ci-bot
          icon_url: "((slack.icon))"
          text:    "((slack.fail_url)) haproxy-boshrelease : unit-tests job failed"

  - name: unit-tests-pr
    public: true
    serial: true
    plan:
    - do:
      - { get: git-pull-requests, trigger: true, version: every }
      - put: git-pull-requests
        params:
          path: git-pull-requests
          status: pending
          context: unit-tests
      - task: lint
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: iacbox.common.repositories.cloud.sap/haproxy-boshrelease-testflight
              tag:        latest
              username:   ((docker.username))
              password:   ((docker.password))
          inputs:
            - { name: git-pull-requests }
          caches:
          - path: git-pull-requests/vendor/cache
          - path: git-pull-requests/.bundle
          run:
            path: ./git-pull-requests/ci/scripts/lint
            args: []
          params:
            REPO_ROOT: git-pull-requests
      - task: unit-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: iacbox.common.repositories.cloud.sap/haproxy-boshrelease-testflight
              tag:        latest
              username:   ((docker.username))
              password:   ((docker.password))
          inputs:
            - { name: git-pull-requests }
          caches:
          - path: git-pull-requests/vendor/cache
          - path: git-pull-requests/.bundle
          run:
            path: ./git-pull-requests/ci/scripts/unit-tests
            args: []
          params:
            REPO_ROOT: git-pull-requests
    on_success:
      put: git-pull-requests
      params:
        path: git-pull-requests
        status: success
        context: unit-tests
    on_failure:
      put: git-pull-requests
      params:
        path: git-pull-requests
        status: failure
        context: unit-tests


  - name: acceptance-tests
    public: true
    serial: true
    plan:
    - do:
      - in_parallel:
        - { get: git, trigger: true, passed: [unit-tests] }
        - { get: stemcell }
        - { get: stemcell-bionic }
        - { get: bpm }
      - task: acceptance-tests
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: iacbox.common.repositories.cloud.sap/haproxy-boshrelease-testflight
              tag:        latest
              username:   ((docker.username))
              password:   ((docker.password))
          inputs:
            - { name: git }
            - { name: stemcell }
            - { name: stemcell-bionic }
            - { name: bpm }
          run:
            path: ./git/ci/scripts/acceptance-tests
            args: []